services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: 
      POSTGRES_USER: 
      POSTGRES_PASSWORD: 
      TZ: Europe/Madrid
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  mailhog:
    image: mailhog/mailhog:latest
    container_name: mailhog
    ports:
      - "1025:1025"   # SMTP
      - "8025:8025"   # Web UI

  n8n:
    image: naskio/n8n-python:latest
    container_name: n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - DB_TYPE=postgres
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=
      - DB_POSTGRESDB_USER=
      - DB_POSTGRESDB_PASSWORD=
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=
      - GENERIC_TIMEZONE=Europe/Madrid
      - TZ=Europe/Madrid
    depends_on:
      - postgres
      - mailhog
    volumes:
      - n8n_data:/home/node/.n8n
      - ./scripts:/home/node/scripts

volumes:
  postgres_data:
  n8n_data: